import { DashNavBar } from "@/components/DashNavBar";

export const metadata = {
  title: "Dashboard | Aina's App",
  description: "Generated by create next app",
};

export default function DashLayout({ children }) {
  return (
    <>
      <DashNavBar />
      {children}
    </>
  );
}
